### ISSUE TITLE
TO DO LIST

### ISSUE THREAD

**Issue by NotoriousMKD** [NotoriousMKD/turtleislandgatsby#1]
- [ ] copy over existing blog content
- [x] copy over Project Overview
- [ ] add contact info to Contact page
- [ ] find out if they want a contact form and get it working
- [ ] update the site navigation
- [ ] create a new biographies resource
- [ ] figure out what goes on the homepage 
- [ ] update some branding - icon, favicon, document titles, find either real images or reasonable replacement images for coffee shop crap
- [ ] ask Kelsey if she will do a design consultation with me 
- [ ] add structured data to every blog post (date, location, tribe, etc.) 
- [ ] try to get automatic deploys working 
- [ ] associate all of these accounts to a new email (github, netlify)
- [ ] create test subdomain 
- [ ] gather and upload images for the bios
- [ ] map

**Comment by NotoriousMKD** [comment]
Bios frontmatter / `admin/config.yml`

```yml
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tribe", name: "tribe", widget: "string" }
      - { label: "Region", name: "region", widget: "string" }
      - { label: "State", name: "state", widget: "string" }
      - { label: "Birth Year", name: "birthyear", widget: "datetime" }
      - { label: "Death Year", name: "deathyear", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
```
